name: GADRP
channels:
  - conda-forge
  - pytorch
  - nvidia
dependencies:
  - python=3.7.10
  - scikit-learn=0.24.2
  - numpy=1.19.2
  - pandas=1.3.4
  - pytorch::pytorch=1.9.0
  - nvidia::cudatoolkit=10.2
  - scipy=1.7.3
  - pip
  - pip:
    - --find-links https://pytorch-geometric.com/whl/torch-1.9.0+cu102.html torch-scatter==2.0.9
    - --find-links https://pytorch-geometric.com/whl/torch-1.9.0+cu102.html torch-sparse==0.6.12
    - --find-links https://pytorch-geometric.com/whl/torch-1.9.0+cu102.html torch-cluster==1.5.9
    - --find-links https://pytorch-geometric.com/whl/torch-1.9.0+cu102.html torch-spline-conv==1.2.1
    - torch-geometric==2.3.1
